### ISSUE TITLE
GraalVM/Native-image

### ISSUE THREAD

**Issue by mipastgt** [dustinkredmond/NotiFX#1]
Whatever the outcome of this project is, it should work with Gluons GraalVM/Native-image toolchain. This would however exclude any features which were introduced after Java 11. Especially this would exclude the use of the Foreign Linker API.

**Comment by dustinkredmond** [comment]
@mipastgt A few folks started NotiFX with the intention of nearly exclusively using the Foreign Linker API, so until GraalVM supports this API, NotiFX will not work with the toolchain. However, as the Foreign Linker API is still an incubating project, this repo was created for public use in the far future.

NotiFX was sort of created as an off-shoot of my [FXTrayIcon](https://github.com/dustinkredmond/FXTrayIcon) with the intention of native-style notifications. FXTrayIcon should in theory be able to be used with the GraalVM toolchain, as it's implemented solely in JavaFX and AWT.

**Comment by mipastgt** [comment]
I doubt that JavaFX can afford to further delay innovations into "the far future". Just my two €ent.

**Comment by dustinkredmond** [comment]
@mipastgt I appreciate your input. What would your suggestions be to handling native looking notifications? Would it be preferred to use JNI, create custom JavaFX controls, or another means to which I'm not aware of? The one issue that I'm running into is the lack of support for creating system tray icons without the use of AWT, though I suppose we could just use JNI if it came down to it.

**Comment by mipastgt** [comment]
JNI is a safe bet. It's not as cool as the Foreign Linker API but it works also for current and older Java releases. Currently there are also some issues with JNA, so I'd stick with good old JNI. If the access layer is well enough encapsulated, one could even play with both approaches if there is enough interest.

**Comment by dustinkredmond** [comment]
@mipastgt Thank you. As much as I love what has been done with the Foreign Linker API, I guess it's time to dust off the 'ole JNI books again. I will raise this issue with others.

**Comment by mkarg** [comment]
Well, contribute whatevery you want. For me, I do not have the time to tinker with C++ every again, so I definitively will *only* contribute the Foreign Linker calls Win32 code, and somebody else may then feel free to convert it to any toolchain he likes. :-)

**Comment by dustinkredmond** [comment]
@mkarg I'm not averse to Foreign Linker calls a bit. I feel as though one day its usage will be quite common, as will other incubating Java features. If GraalVM doesn't want to implement them, that sounds more like Gluon's problem than NotiFX's. I may consider a branch that does use JNI. I'm not very familiar with Win32 but if you write the Foreign Linker calls, I can easily translate to JNI calls. I might give GNOME and KDE Linux desktop environment implementations a shot tonight after work.
